### ISSUE TITLE
Hi I am using unity2018.2 to open the project error

### ISSUE THREAD

**Issue by spartancc** [vrm-c/UniVRMTest#6]
Hi I am using unity2018.2 to open the project error, thank you for your help.
![a](https://user-images.githubusercontent.com/42367711/51294805-98372480-1a4f-11e9-9b45-e2fde1b09809.png)

**Comment by ousttrue** [comment]
I will investigate.

**Comment by PoChang007** [comment]
Hi,
Please delete the 'VRM.Samples' folder and try it again. 
I made it work in Unity 2018.30f2 version by this way. I think it also works for unity2018.2.

I recommend to upgrade the UniVRM and UniVRM-samples to v0.48 in your project.
https://github.com/dwango/UniVRM/releases
Make sure the existing VRM and VRM.Sample folders are deleted before v0.48 packages import. 


<img width="1106" alt="unity 2018 3 0f2_vrmviewer" src="https://user-images.githubusercontent.com/17579532/51306747-75bdff00-1a81-11e9-8b95-580eba66c9f9.png">

**Comment by spartancc** [comment]
Thank you for your help, no problem after re-importing.
