### ISSUE TITLE
How about using UnitySimpleFileBrowser?

### ISSUE THREAD

**Issue by MoorDev** [vrm-c/UniVRMTest#8]
https://github.com/yasirkula/UnitySimpleFileBrowser
https://assetstore.unity.com/packages/tools/gui/runtime-file-browser-113006

Thanks for Simple VRM Viewer.

But, I want to VRM viewing on macOS and Linux. 
So, Your sources put on Unity for Linux. 
"FileDialogForWindows.FileDialog" method error!!

This method is only for Windows.

I want build for Linux system. So,
[ViewerUI.cs.zip](https://github.com/dwango/UniVRMTest/files/2966511/ViewerUI.cs.zip)
I modified like here.
using UnitySimpleFileBrowser and Overwrite /Assets/VRMViewer/Scripts for 1.04.

I can build for Linux and macOS.
If you want that build for Android too!

VRM is great format. 

I don't know how to using diff or patch. So, I upload one of source file. Sorry.

Unity3D 2018.3.5f1

**Comment by PoChang007** [comment]
Thanks for your suggestion. I will test it soon. It's always good to make the program more general.

Also, I can manually add Korean version you provided before from pull request. It won't take too much time for me to do that.

**Comment by PoChang007** [comment]
Quick update: I got linux build succeeded but haven't managed to get the Viewer running in my virtual machine. I will try it again later or probably add/point out this feature for people who may be interested in non-windows platform build.

Thanks,

**Comment by PoChang007** [comment]
done. sorry for dragging on for a long time.
